config/routes.rb
Rails.application.routes.draw do

  #homeルート
  root "home#index"

  # ログイン処理を分ける前のルート
  # 現状は動いているがエラーになった場合いつでも使えるようにコメントアウト
  #userルート
  # get "login" => "users#login_form"
  # post "login" => "users#login"
  # post "logout" => "users#logout"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  post "logout" => "sessions#destroy"

  #postルート
  get "posts/new_category" => "posts#new_category"

  #いいねルート
  post 'post_like/:id' => 'post_likes#create', as: 'create_post_like'
  delete 'post_like/:id' => 'post_likes#destroy', as: 'destroy_post_like'

  # tweetのlike
  post 'tweet_like/:id' => 'tweet_likes#create', as: 'create_tweet_like'
  delete 'tweet_like/:id' => 'tweet_likes#destroy', as: 'destroy_tweet_like'

  resources:tweets, except: [:show]
  resources:categories, except: [:show]
  resources:users, except: [:index] do
    member do
      get :following, :followers
    end
  end
  resources:posts, except: [:show]
  resources:relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # users テーブルにパスワードを保存するとき、パスワードを暗号化して保存してくれる
  has_secure_password

  # {}があると
  # undefined method `to_sym' for {:presence=>true}:Hashエラー文が出てしまう
  validates :name, presence: true, uniqueness: true, length: { maximum: 10 }
  validates :email, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
  validates :password_digest, presence: true
  
  # リレーション,postsが多の関係性,dependent: :destroyはそのモデル(user)が削除されたら、紐づいているモデル(posts)も削除するというもの
  has_many :posts, dependent: :destroy
  has_many :categories, dependent: :destroy
  has_many :tweets, dependent: :destroy

  # いいね
  has_many :post_likes, dependent: :destroy
  has_many :tweet_likes, dependent: :destroy

  # フォロー
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy

  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # ユーザーをフォローする
  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをアンフォローする
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end

  # いいねの判定
  def post_liked_by?(post_id)
    post_likes.exists?(post_id:)
  end

  def tweet_liked_by?(tweet_id)
    tweet_likes.exists?(tweet_id:)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # @user = User.find(params[:id])をメソッド化している
  before_action :set_user, only: %i[show edit update destroy]

  # ログイン状態じゃないと見れないページ, application_controller.rbに記述がある
  before_action :authenticate_user, only: %i[show edit update following followers]

  # ログイン状態のページ制限, application_controller.rbに記述がある
  before_action :forbid_login_user, only: %i[new create login_form login]

  # 正しいユーザーかを確かめるメソッド ログインしてるIDとひとしくないと編集できない様にしてる
  before_action :ensure_correct_user, only: %i[edit update destroy]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # デフォで最初にcategory :nameを作ってあげる
      Category.create(name: "無し", user_id: @user.id)
      session[:user_id] = @user.id
      flash[:notice] = "ユーザー登録が完了しました"
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @user.update(user_params)
      flash[:notice] = "更新しました"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:notice] = "ユーザーを削除しました"
    redirect_to root_path
  end

  # フォローページの処理
  def following
    @title = "フォロー"
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  # ログイン処理を分ける前のコード
  # 現状は動いているがエラーになった場合いつでも使えるようにコメントアウト
  # def login_form; end

  # def login
  #   @user = User.find_by(
  #     email: params[:email],
  #     password_digest: params[:password]
  #   )
  #   if @user
  #     session[:user_id] = @user.id # ここに追加
  #     flash[:notice] = "ログインしました"
  #     redirect_to user_path(@user.id)
  #   else
  #     @error_message = "メールアドレスまたはパスワードが間違っています"
  #     @email = params[:email]
  #     render :login_form
  #   end
  # end

  # def logout
  #   session[:user_id] = nil
  #   flash[:notice] = "ログアウトしました"
  #   redirect_to login_path
  # end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password)
  end

  def ensure_correct_user
    return if @current_user.id == @user.id

    flash[:notice] = "権限がありません"
    redirect_to user_path(@current_user)
  end
end

app/views/users/_follow.html.erb
<%= form_for(@current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォロー", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if @user != @current_user %>
  <div id="follow_form">
  <% if @current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with model: user do |f| %>
  <%= f.label :name ,"ユーザー名" %><br>
  <%= f.text_field :name, class: "user_form" , maxlength: "10" , placeholder: "1文字以上,10文字以内" %><br>
  <%= f.label :email ,"メールアドレス" %><br>
  <%= f.text_field :email, class: "user_form" %><br>
  <%= f.label :password ,"パスワード" %><br>
  <%= f.password_field :password, placeholder: "4文字以上,10文字以内", class: "user_form" %><br>
  <%= f.submit "登録" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(@current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "フォロー解除", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<div class="main users-edit">
  <div class="container">
    <div class="form-heading">ユーザー情報の編集</div>
    <div class="form users-form">
      <div class="form-body">
        <%= render "layouts/error_message", user: @user %>
        <%= render "form", user: @user %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="main users-new">
  <div class="container">
    <div class="form-heading">新規ユーザー登録</div>
    <div class="form users-form">
      <div class="form-body">
        <%= render "layouts/error_message", user: @user %>
        <%= render "form", user: @user %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="main user-show">
  <div class="container">
    <div class="user">
      <h2><%= @user.name %></h2>
      <p><%= @user.email if @current_user.id == @user.id %></p>
      <%= link_to "編集", edit_user_path if @current_user.id == @user.id %>
      <%= link_to "退会", user_path(@user), method: :delete, data: { confirm: "本当に削除しますか？?" } if @current_user.id == @user.id %>
      <div class="post_btn">
        <%= link_to "明細を登録", new_post_path, class: "btn" %>
        <%= link_to "カテゴリ一覧", categories_path, class: "btn" %>
        <%= link_to "自分の明細一覧", posts_path, class: "btn" %>
        <%= link_to "つぶやく", tweets_path, class: "btn" %>
      </div>
    </div>
      <section class="stats" id="user_<%= @user.id %>">
        <%= render 'relationships/stats' %>
      </section>
      <%= render 'follow_form' %>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1><%= @user.name %></h1>
      <span><%= link_to "プロフィールを見る", @user %></span>
    </section>
    <section class="stats">
      <%= render 'relationships/stats' %>
      <h3><%= @title %></h3>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to user.name, user %><br>
          <% end %>
        </div>
    </section>
  </aside>
</div>