config/routes.rb
Rails.application.routes.draw do

  #homeルート
  root "home#index"

  # ログイン処理を分ける前のルート
  # 現状は動いているがエラーになった場合いつでも使えるようにコメントアウト
  #userルート
  # get "login" => "users#login_form"
  # post "login" => "users#login"
  # post "logout" => "users#logout"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  post "logout" => "sessions#destroy"

  #postルート
  get "posts/new_category" => "posts#new_category"

  #いいねルート
  post 'post_like/:id' => 'post_likes#create', as: 'create_post_like'
  delete 'post_like/:id' => 'post_likes#destroy', as: 'destroy_post_like'

  # tweetのlike
  post 'tweet_like/:id' => 'tweet_likes#create', as: 'create_tweet_like'
  delete 'tweet_like/:id' => 'tweet_likes#destroy', as: 'destroy_tweet_like'

  resources:tweets, except: [:show]
  resources:categories, except: [:show]
  resources:users, except: [:index] do
    member do
      get :following, :followers
    end
  end
  resources:posts, except: [:show]
  resources:relationships, only: [:create, :destroy]
end

app/controllers/home/tops_controller.rb
class Home::TopsController < ApplicationController
  def top; end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :forbid_login_user, only: [:index]

  def index; end
end

app/views/home/index.html.erb
<div class="top-wrapper">
  <div class="container">
    <h2> 家計簿アプリ</h2>
    <p>
      家計簿の目的は自分の<br>
      消費動向を把握して、無駄遣いをしないようにすることです
    </p>
    <p>このアプリは無駄使いをしているあなたを救いたいアプリ</p>
    <div class="btn-wrapper">
      <%= link_to "会員登録", new_user_path, class: "btn signup" %>
      <p>すでにアカウント作成済みの方</p>
      <%= link_to "ログイン", login_path, class: "btn login" %>
    </div>
  </div>
</div>