config/routes.rb
Rails.application.routes.draw do

  #homeルート
  root "home#index"

  # ログイン処理を分ける前のルート
  # 現状は動いているがエラーになった場合いつでも使えるようにコメントアウト
  #userルート
  # get "login" => "users#login_form"
  # post "login" => "users#login"
  # post "logout" => "users#logout"

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  post "logout" => "sessions#destroy"

  #postルート
  get "posts/new_category" => "posts#new_category"

  #いいねルート
  post 'post_like/:id' => 'post_likes#create', as: 'create_post_like'
  delete 'post_like/:id' => 'post_likes#destroy', as: 'destroy_post_like'

  # tweetのlike
  post 'tweet_like/:id' => 'tweet_likes#create', as: 'create_tweet_like'
  delete 'tweet_like/:id' => 'tweet_likes#destroy', as: 'destroy_tweet_like'

  resources:tweets, except: [:show]
  resources:categories, except: [:show]
  resources:users, except: [:index] do
    member do
      get :following, :followers
    end
  end
  resources:posts, except: [:show]
  resources:relationships, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user # リレーション, userは1の関係性
  belongs_to :category
  has_many :post_likes, dependent: :destroy
  has_one_attached :image # アクティブストレージを使うための記述

  # ばりでーしょん
  validates :category_id, presence: true
  validates :price, numericality: { only_integer: true }
  validates :memo, length: { maximum: 20 }

  # スコープ
  # eager_loadスコープ,{Post.joins(:category)}でアソシエーションできるんだけどscopeだとPostを省略しないといけない
  # 画像はしょうがないから弾く, image_attachmentとblob
  scope :eager_load_category, -> { eager_load(:category) }
  # scope :price, -> (price){ where('cast(price as text) = ? ', "#{price}")} 参考文 スコープで使用する場合引数を渡す必要がある
  #                    ↑引数
  scope :keyword, ->(keyword) { where('memo LIKE ?', "%#{keyword}%") if keyword.present? }
  # 曖昧検索は%を外す
  # 完全一致検索    =   を使う
  scope :prices, ->(price) { where('price = ? ', price) if price.present? }

  # 元は"#{use_day}", "#{end_day}"だったがruboの警告でto_sに変更
  # ruboで変わり果てた姿になったから元のコードを置いとく
  # scope :use_day, ->(use_day, end_day) {where("use_day BETWEEN ? AND ? ", use_day.to_s, end_day.to_s) if use_day.present? && end_day.present? }
  scope :use_day, lambda { |use_day, end_day|
                    if use_day.present? && end_day.present?
                      where("use_day BETWEEN ? AND ? ", use_day.to_s, end_day.to_s)
                    end
                  }
end

app/controllers/posts/new_category_controller.rb
class Posts::NewCategoryController < ApplicationController
  
  # TODO: 恐らく削除
  def new_category
    # Category.newは受け皿, paramsはフォームで送った文を取得, ストロングパラメータは許可したいカラムのみ
    # 今回だとuser_idはログインしてるidで登録したいので弾く
    @category = Category.new(params.require(:category).permit(:name))
    @category.user_id = @current_user.id
    @category.save
    @post = Post.new(params.require(:post).permit(:memo, :price, :use_day))
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[edit update destroy] # findをメソッド化している

  # ログイン状態じゃないと見れないページ, application_controller.rbに記述がある
  before_action :authenticate_user

  # 正しいユーザーかを確かめるメソッド ログインしてるIDとひとしくないと編集できない様にしてる
  before_action :ensure_correct_post, only: %i[edit update destroy]

  def index
    # all以外に何かくっつける場合はallはいらないです
    # order(use_day: "DESC")で並び替え
    @posts = @current_user.posts.eager_load_category.keyword(params[:keyword]).prices(params[:prices]).use_day(
      params[:use_day], params[:end_day]
    ).order(use_day: "DESC")
  end

  def new
    @post = Post.new
    @categories = @current_user.categories
    # ここでidを選択する事によってラジオボタンが選択されているようになる
    # 仕組みは検証のvalueの値と一致していれば選択されるようになっている
    @post.category_id = @categories.first.id
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      flash[:notice] = "投稿できました"
      redirect_to posts_path
    else
      render :new
    end
  end

  def edit
    @categories = @current_user.categories
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "更新しました"
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "削除しました"
    redirect_to posts_path
  end

  # 後ほど変更
  # def new_category
  #   # Category.newは受け皿, paramsはフォームで送った文を取得, ストロングパラメータは許可したいカラムのみ
  #   # 今回だとuser_idはログインしてるidで登録したいので弾く
  #   @category = Category.new(params.require(:category).permit(:name))
  #   @category.user_id = @current_user.id
  #   @category.save
  #   @post = Post.new(params.require(:post).permit(:memo, :price, :use_day))
  # end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    # マージメソッドでuser_idを上書きしている
    params.require(:post).permit(:memo, :user_id, :category_id, :price, :use_day,
                                 :image).merge(user_id: @current_user.id)
  end

  def ensure_correct_post
    return if @current_user.id == @post.user_id

    flash[:notice] = "権限がありません"
    redirect_to posts_path
  end
end

app/views/posts/_ajax.html.erb
<div id="ajax">
  <%= form_with model: post do |f| %>
    <h1>カテゴリ一覧</h1>
    <% @current_user.categories.each do |category| %>
      <%= f.radio_button :category_id, category.id %>
      <%= f.label :category_id, category.name %><br>
    <% end %>
    <p>↓ここに追加したいカテゴリーを入力してね↓</p><br>
    <%= f.text_field :category_name, id: 'text_box', maxlength: "20", placeholder: "20文字以内" %>
    <%# TODO: 後ほど変更 controllerオプションのとこ %>
    <%= link_to "カテゴリ追加ボタン", { controller: 'new_category', action: 'new_category' ,remote: true }, { id: "link", class: "btn", onclick: "makeParams()" } %><br>
    <%= f.label :image, "画像" %><br>
    <%= f.file_field :image, id: "image" %><br>
    <%= f.label :use_day, "使った日" %><br>
    <%= f.date_field :use_day, id: "use_day" %><br>
    <%= f.label :memo ,"メモ" %><br>
    <%= f.text_field :memo, id: "memo", maxlength: "20", class: "post_form", placeholder: "20文字以内" %><br>
    <%= f.label :price ,"¥価格" %><br>
    <%= f.text_field :price, id: "price", maxlength: "10", class: "post_form" %><br>
    <%= f.submit "登録" %>
  <% end %>
</div>

app/views/posts/_error_message.html.erb
<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |message| %>
    <div class="form-error">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/posts/_form.html.erb
<%= render "ajax", post: @post %>
<%# ここの関数の処理はストロングパラメーターに通すパラメーターを作っている %>
<script type="text/javascript">
  // 全てのfieldにidを付与させて、ここで定数に格納
  const text_box = document.getElementById("text_box");
  const image = document.getElementById("image");
  const use_day = document.getElementById("use_day");
  const memo = document.getElementById("memo");
  const price = document.getElementById("price");
  
  // onclickにmakeParamsと命名してこの処理が動く
  function makeParams() {
    // 入力した値をvalueで出力して変数に格納
    let memoParams = memo.value
    let priceParams = price.value
    let category_nameParams = text_box.value
    let use_dayParams = use_day.value

    // 出力した値を結合
    // なぜ"post[memo]="かというとlabelでつけたname属性をrails側が変換している
    // このような変換をしないとストロングパラメーターが動かない
    let memoResult = "post[memo]=" + memoParams
    let priceResult = "post[price]=" + priceParams
    let category_nameResult = "category[name]=" + category_nameParams
    let use_dayResult = "post[use_day]=" + use_dayParams

    // resultで最終的に通るパラメータに組み立ている
    // get通信で複数のパラメーターを作りたい場合"&"を使う
    // ？は、URLとクエリストリングの区切りを示す記号です

    let result = "<%= posts_new_category_path %>" + "?" + memoResult + "&" + priceResult + "&" + category_nameResult + "&" + use_dayResult
    let link = document.getElementById("link");

    // リンクをセーブしている ()の中身でhrefを書き換え、encodeURIで使えるurlに変換される
    // 本来urlに日本語が使えない、encodeURIを使うことによってコードに変換されている
    link.setAttribute('href', encodeURI(result))
  }
</script>

app/views/posts/edit.html.erb
<div class="main posts-new">
  <div class="container">
    <div class="form-heading">編集</div>
    <div class="form posts-form">
      <div class="form-body">
        <%= render "form", post: @post %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<h3 class="post_h3">明細一覧</h3>
<%= render "layouts/search" %>
<div class="count_record">
  <h4>現在の日にち<%= Date.current.strftime("%Y年 %m月 %d日")%>投稿数<%= @posts.size %> 件 </h4>
  <h4>合計金額¥<%= @posts.map(&:price).sum %> 円 </h4>
</div>
<table>
  <thead>
    <tr>
      <th>ブックマーク</th>
      <th>画像</th>
      <th>メモ</th>
      <th>使った日</th>
      <th>価格</th>
      <th>カテゴリー</th>
      <th>編集</th>
      <th>消去</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td id="post_<%= post.id %>">
          <%= render "post_likes/post_like", post: post %>
        </td>
        <% if post.image.attached? %>
          <td><%= image_tag post.image, class: "post_image" %></td>
        <% else %>
          <td></td>
        <% end %>
        <td><%= post.memo %></td>
        <td><%= post.use_day %></td>
        <td><%= post.price %></td>
        <td><%= post.category.name %></td>
        <td><%= link_to "編集", [:edit, post] %></td>
        <td><%= link_to "削除", post, method: :delete, data: { confirm: "本当に削除しますか？" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="post_btn">
  <%= link_to "明細を登録", new_post_path, class: "btn" %>
  <%= link_to "カテゴリ一覧", categories_path, class: "btn" %>
</div>

app/views/posts/new.html.erb
<div class="main posts-new">
  <div class="container">
    <div class="form-heading">新規作成</div>
    <div class="form posts-form">
      <div class="form-body">
        <%= render "error_message", post: @post %>
        <%= render "form", post: @post %>
      </div>
    </div>
  </div>
</div>

app/views/posts/new_category.js.erb
document.getElementById('ajax').innerHTML = '<%= j(render "ajax", category: @categories, post: @post ) %>'